### ISSUE TITLE
A question: is this/will this ever be updated?

### ISSUE THREAD

**Issue by foxsouns** [1j01/sbahjifier#1]
Hey, came across this and was wondering if that Firefox extension would ever come out? I'm really interested in having fun with this, but I don't use Chrome. Thanks!

**Comment by 1j01** [comment]
I just updated this extension (fixed a bunch of things), got it working in Firefox and submitted to Firefox Addons. It's pending review.
If it passes review it should be available here: https://addons.mozilla.org/en-US/firefox/addon/1j01-sbahjifier/

**Comment by foxsouns** [comment]
woah, awesome! tried doing that myself, but hit a bunch of dead ends, seeing as i have no idea how to program in ANY language, let alone javascript haha
thanks for getting back to a small fan of a simple browser extension!

**Comment by 1j01** [comment]
[Alright, it got approved!](https://addons.mozilla.org/en-US/firefox/addon/1j01-sbahjifier/)
